<a href="https://colab.research.google.com/github/PajrulPalah/data_analysis_bootcamp/blob/main/phyton/Python_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **FUNCTIONS**

Fungsi adalah blok kode terorganisir dan dapat digunakan kembali yang digunakan untuk melakukan sebuah tindakan/action. Fungsi memberikan modularitas yang lebih baik untuk aplikasi Anda dan tingkat penggunaan kode yang tinggi.

### Mendefinisikan Fungsi

Anda dapat menentukan fungsi untuk menyediakan fungsionalitas yang dibutuhkan. Berikut adalah aturan sederhana untuk mendefinisikan fungsi dengan Python.

* Fungsi blok dimulai dengan def kata kunci diikuti oleh nama fungsi dan tanda kurung (()).
* Setiap parameter masukan atau argumen harus ditempatkan di dalam tanda kurung ini. Anda juga dapat menentukan parameter di dalam tanda kurung ini.
Pernyataan pertama dari sebuah fungsi dapat berupa pernyataan opsional - string dokumentasi fungsi atau docstring.
* Blok kode dalam setiap fungsi dimulai dengan titik dua (:) dan indentasi.
*Pernyataan kembali [ekspresi] keluar dari sebuah fungsi, secara opsional menyampaikan kembali ekspresi ke pemanggil. Pernyataan pengembalian tanpa argumen sama dengan return None.

In [ ]:
def printme( str ):
    "This prints a passed string into this function"
    print (str)
    #return

In [ ]:
printme("belajar masak")

belajar masak


### Argumen dalam Fungsi Python
> Saat mendefinisikan fungsi di Python, Kita perlu memasukan Argumen ke dalam fungsi dengan meletakkannya di dalam tanda kurung.



In [ ]:
def addNum(num1, num2):
    print(num1 + num2)

In [ ]:
addNum(2, 5)

7


In [ ]:
addNum(2, -9)

-7


Dari contoh diatas, kita mendefinisikan fungsi bernama ``` addNum() ``` yang memiliki 2 argumen yang kemudian memanggilnya dengan nilai untuk 2 argumen yang ditentukan.

In [ ]:
#def greet():
#    print('Hello, Colion')

def greet(who="Colin"):
    print("Hello,", who)

Dari contoh di atas, kita mendefinisikan fungsi yang memiliki arguments ‘who’. Di dalam fungsi tersebut kita mengassign nilai “Colin” terhadap argumen ‘who’. Ini menunjukan, jika kita tidak memberikan nilai ‘who’ ketika kita memanggil fungsi tersebut.,maka fungsi tersebut akan memiliki nilai argument ‘who’ sebagai “Colion”.

In [ ]:
## memanggil fungsi tanpa memberikan nilai untuk argumentt who
greet()

Hello, Colin


In [ ]:
# memanggil fungsi dengan memiliki argument who
greet(who="Mba Susi")

Hello, Mba Susi


In [ ]:
# memanggil fungsi dengan memberikan argument untuk nilai who
greet("Fauzan")

Hello, Fauzan


### Menggunakan Kata Kunci ```return```
> ```return``` digunakan untuk keluar dari sebuah fungsi sehingga fungsi tersebut kembali ke tempat ia dipanggil. Artinya, mnengirim sesuatu keluar dari fungsi.

> Pernyataan ```return``` dapat berisi ekspresi yang akan dieksekusi setelah fungsi dipanggil.

In [ ]:
def multiplyNum(num1 = 3):
    return num1 * 8

result = multiplyNum(num1=9)
print(result)

72


* Kita mendefinisikan sebuah fungsi bernama ```multiplyNum``` dan memasukan num1 sebagai argumen
* Di dalam fungsi tersebut, Kita menggunakan kata kunci ```return``` untuk menentukan bahwa kita ingin argumen num1 dikalikan dengan 8
* Setelah itu, kita memanggil fungsi tersebut, memasukan 8 ke dalamnya sebagai nilai untuk argumen num1, dan menetapkan pemanggilan fungsi tersebut ke variabel yang kita beri nama result
*Dengan variabel hasil, kita dapat mencetak apa yang ingin kita lakukan dengan fungsi tersebut.

In [ ]:
# rumus menghitung volume balok

def vol_balok(p=3, l=5, t=4):
  v = p*l*t
  return v

In [ ]:
vol_balok()

60

# **NUMPY**

**NumPy (Numerical Python)** adalah library Python yang fokus pada scientific computing.. Dalam penggunaan numpy, kita perlu melakukan importing terlebih dahulu.

In [3]:
import numpy as np

### Numpy Attributes
Berikut terdapat beberapa contoh penggunaan atribut dari Numpy:

* **Dimension**, digunakan untuk melihat dimensi yang dimiliki suatu numpy array
* **Shape**, digunakan untuk mengetahui berapa jumlah baris dan kolom dari suatu numpy array
* **type**, digunakan untuk mengetahui tipe data yang dimiliki suatu numpy array
* **itemsize**, untuk mwlihat ukuran memori yang dibutuhkan untuk menyimpan sebuah numpy array
* **nbytes**, digunakan untuk menghitung total bytes yang dimiliki suatu numpy array.

In [4]:
# Membuat list array dengan numpy
my_numpy = np.array([
                    [1,2,3,4,5],
                    [6,7,8,9,0.5]
                    ])

my_numpy

array([[1. , 2. , 3. , 4. , 5. ],
       [6. , 7. , 8. , 9. , 0.5]])

In [ ]:
# dimensi
my_numpy.ndim

2

In [ ]:
# shape
my_numpy.shape

(2, 5)

In [ ]:
# type
my_numpy.dtype

dtype('float64')

In [ ]:
# itemsize
my_numpy.itemsize

8

In [ ]:
# nbytes
my_numpy.nbytes

80

### Indexing Arrays

In [ ]:
my_numpy

array([[1. , 2. , 3. , 4. , 5. ],
       [6. , 7. , 8. , 9. , 0.5]])

In [ ]:
my_numpy[1][2:]

array([8. , 9. , 0.5])

### Slicing Array

In [ ]:
# [start : stop :step]
nmp = np.array(range(10))

In [ ]:
nmp

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
nmp[0:6:2]

array([0, 2, 4])

In [ ]:
# multidimension
my_numpy[1:,2:]

array([[8. , 9. , 0.5]])

### Reshapping Array

In [ ]:
my_numpy.transpose()

array([[1. , 6. ],
       [2. , 7. ],
       [3. , 8. ],
       [4. , 9. ],
       [5. , 0.5]])

In [ ]:
my_numpy.reshape(5,2)

array([[1. , 2. ],
       [3. , 4. ],
       [5. , 6. ],
       [7. , 8. ],
       [9. , 0.5]])

In [5]:
my_numpy.reshape(10,1)

array([[1. ],
       [2. ],
       [3. ],
       [4. ],
       [5. ],
       [6. ],
       [7. ],
       [8. ],
       [9. ],
       [0.5]])

In [ ]:
my_numpy.reshape(1, 10)

array([[1. , 2. , 3. , 4. , 5. , 6. , 7. , 8. , 9. , 0.5]])

In [6]:
my_numpy.reshape(2, 5)

array([[1. , 2. , 3. , 4. , 5. ],
       [6. , 7. , 8. , 9. , 0.5]])

### Joining Array

In [ ]:
my_numpy = np.array([
                    [1,2,3,4,5],
                    [6,7,8,9,'sapi']
                    ])

nmpy = np.array([
                #[1,2,3,1],
                [2,3,5,3,2]
                ])

np.concatenate([my_numpy, nmpy])

array([['1', '2', '3', '4', '5'],
       ['6', '7', '8', '9', 'sapi'],
       ['2', '3', '5', '3', '2']], dtype='<U21')

In [ ]:
my_numpy = np.array([
                    [1,2,3,4,5],
                    [6,7,8,9,'sapi']
                    ])

In [ ]:
# dimensi
my_numpy.ndim

2

In [ ]:
# shape
my_numpy.shape

(2, 5)

In [ ]:
# type
my_numpy.dtype

dtype('<U21')

In [ ]:
# itemsize
my_numpy.itemsize

84

In [ ]:
nmpy*2

array([[ 4,  6, 10,  6,  4]])

# **PANDAS**

> **Pandas** adalah suatu library yang open source, menyediakan performance yang sangat baik, struktur data yang mudah digunakan dan alat analisis data untuk Python.

> Untuk menggunakan pandas, kita terlebih dahulu perlu menginstall nya  dengan mengetikan ```pip install pandas```.



In [ ]:
import pandas as pd

## Series VS Data Frame

**Series** dan **Dataframe** ini adalah suatu objek tempat kita menyimpan data secara terstruktur. Perbedaan dari Series dan DataFrame ini terletak pada strukturnya dan juga attribute dan method-method yang mereka miliki, untuk perbedaan strukturnya adalah sebagai berikut :

1. Series adalah objek 1 dimensi
2. DataFrame adalah suatu objek 2 dimensi, mirip seperti tabel

## Series

Series adalah suatu objek satu dimensi yang dapat menyimpan berbagai jenis tipe data seperti integer, string, dan lain sebagainya. tipe data dari objek series ini harus seragam.

In [ ]:
x = pd.Series([6,3,4,6])
x

0    6
1    3
2    4
3    6
dtype: int64

Series memiliki satu index saja, dari contoh di atas index tersebut berada baris baris, yaitu 0, 1, 2, 3. kita bisa **mengubah index** tersebut dengan sebagai berikut :

In [ ]:
# cara pertama
x.index = ['a', 'b', 'c', 'd']
x

a    6
b    3
c    4
d    6
dtype: int64

In [ ]:
# cara kedua
x = pd.Series([6,3,4,6], index=['a', 'b', 'c', 'd'])
x

a    6
b    3
c    4
d    6
dtype: int64

### Indexing Series

Untuk melakukan indexing pada objek series, kita perlu menempatkan objek series tersebut sebagai dictionary dan sebagai array.

series as dictionary

In [ ]:
obj_series = pd.Series([1,2,3,4], index=['a','b','c','d'])
obj_series

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
#indexing key
obj_series.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
#indexing value
obj_series.values

array([1, 2, 3, 4])

In [ ]:
#checking existing keys
'zebra' in obj_series

False

Series as array

In [ ]:
# slicing dengan explicit index
obj_series['a':'c']

a    1
b    2
c    3
dtype: int64

In [ ]:
#slicing dengan implicit index
obj_series[:3]

a    1
b    2
c    3
dtype: int64

Indexing menggunakan ```loc``` dan ```iloc``` objek series

* ```loc``` indexing: indexing berdasarkan label objek series sedangkan
* ```iloc``` indexing: indexing berdasarkan posisi objek series

In [ ]:
#.loc indexing
obj_series.loc['c':'d']

c    3
d    4
dtype: int64

In [ ]:
#.iloc indexing
obj_series[2:4]

c    3
d    4
dtype: int64

Filtering objek series

In [ ]:
obj_series[obj_series>2]

c    3
d    4
dtype: int64

In [ ]:
obj_series[['c','d']]

c    3
d    4
dtype: int64

In [ ]:
type(obj_series)

pandas.core.series.Series

## Data Frame

DataFrame adalah suatu objek **2 dimensi** tempat menyimpan data dengan lebih terstruktur. dataframe memiliki 2 index, yaitu index baris dan index columns. Dalam satu column dataframe harus memiliki tipe data yang sama. tapi antar columnnya dataframe bisa memiliki jenis data yang berbeda.

In [ ]:
df = pd.DataFrame({'tipe_int': [50, 21], 'tipe_string': ['a', 'b']})
df

tipe_int tipe_string
0        50           a
1        21           b

In [ ]:
type(df)

pandas.core.frame.DataFrame

### Membaca data dari File

> Membaca data dari file adalah hal pertama yang dilakukan dalam suatu pekerjaan data science. maka hal ini sangat penting.

> Ada beberapa tipe file yang biasa di gunakan untuk menyimpan data, seperti database, excel, csv. disini akan di jelaskan beberapa saja tentang cara membaca file dari berbagai sumber tersebut. akan di jelaskan 2 yaitu csv dan excel karena csv dan excel adalah sumber yang biasa di gunakan untuk menyimpan data karena kemudahannya. ok kita langsung saja.

> Pandas menyediakan metode yang berbeda untuk membaca file dengan tipe berbeda. untuk membaca file bertipe csv pandas menggunakan suatu metode ```read_csv()```, untuk membaca file bertipe excel pandas menggunkan suatu metode bernama ```read_excel()```. perhatikan contoh berikut :

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# membaca dari dari csv
df = pd.read_csv('/content/drive/MyDrive/Materi Data analyst/Data/Salaries.csv')

### Pemeriksaan sederhana tentang karakteristik Data

Pandas memiliki beberapa method untuk memahami gambaran besar karakteristik dari data kita. diantaranya adalah:

* head()
* tail()
* info()
* describe()

In [ ]:
df.head()

id      rank discipline  yrs.since.phd  yrs.service   sex  salary
0   1      Prof          B             19           18  Male  139750
1   2      Prof          B             20           16  Male  173200
2   3  AsstProf          B              4            3  Male   79750
3   4      Prof          B             45           39  Male  115000
4   5      Prof          B             40           41  Male  141500

In [ ]:
df.tail()

id      rank discipline  yrs.since.phd  yrs.service   sex  salary
392  393      Prof          A             33           30  Male  103106
393  394      Prof          A             31           19  Male  150564
394  395      Prof          A             42           25  Male  101738
395  396      Prof          A             25           15  Male   95329
396  397  AsstProf          A              8            4  Male   81035

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   id             397 non-null    int64 
 1   rank           397 non-null    object
 2   discipline     397 non-null    object
 3   yrs.since.phd  397 non-null    int64 
 4   yrs.service    397 non-null    int64 
 5   sex            397 non-null    object
 6   salary         397 non-null    int64 
dtypes: int64(4), object(3)
memory usage: 21.8+ KB


In [ ]:
df.describe()

id  yrs.since.phd  yrs.service         salary
count  397.000000     397.000000   397.000000     397.000000
mean   199.000000      22.314861    17.614610  113706.458438
std    114.748275      12.887003    13.006024   30289.038695
min      1.000000       1.000000     0.000000   57800.000000
25%    100.000000      12.000000     7.000000   91000.000000
50%    199.000000      21.000000    16.000000  107300.000000
75%    298.000000      32.000000    27.000000  134185.000000
max    397.000000      56.000000    60.000000  231545.000000

## Indexing DataFrame

> Akses DataFrame sering juga di kenal indexing atau Subset Selection. secara sederhana maknanya adalah kita memilih suatu data dari baris tertentu dan column tertentu. kita bisa saja memilih beberapa baris dan semua kolom dari data, semua baris dan beberapa column dari data, atau beberapa baris dan bebearpa column dari data.

> Ada banyak cara-cara kita indexing suatu dataframe. diantranya adalah dengan menggunakan :

* ```dataframe[]``` : cara seperti ini dikenal sebagai index operator.
* ```dataframe.kolom``` : cara seperti ini dikenal dengan indexing menggunakan atribut
* ```dataframe.loc[]``` : operator yang menggunakan label untuk mengakses data, jika misalkan kamu melakukan ```dataframe.loc[‘jumlah’]```, berarti kamu hendak mengakses data yang mempunyai index jumlah
dataframe.iloc[: operator yang menggunakan posisi index untuk mengakses data. jikalau kamu melakukan dataframe.iloc[2] berarti kamu hendak mengakses dataframe dengan index posisi 2

In [ ]:
# membaca dari dari csv
#df = pd.read_csv('Salaries.csv')
#df.head()

id      rank discipline  yrs.since.phd  yrs.service   sex  salary
0   1      Prof          B             19           18  Male  139750
1   2      Prof          B             20           16  Male  173200
2   3  AsstProf          B              4            3  Male   79750
3   4      Prof          B             45           39  Male  115000
4   5      Prof          B             40           41  Male  141500

In [ ]:
df['rank'].unique()

array(['Prof', 'AsstProf', 'AssocProf'], dtype=object)

In [ ]:
# indexing operator as series
df['rank']

0          Prof
1          Prof
2      AsstProf
3          Prof
4          Prof
         ...   
392        Prof
393        Prof
394        Prof
395        Prof
396    AsstProf
Name: rank, Length: 397, dtype: object

In [ ]:
#indexing operator as dataframe
df[['rank', 'salary']].head()

rank  salary
0      Prof  139750
1      Prof  173200
2  AsstProf   79750
3      Prof  115000
4      Prof  141500

In [ ]:
# indexing using attribute
df.salary

0      139750
1      173200
2       79750
3      115000
4      141500
        ...  
392    103106
393    150564
394    101738
395     95329
396     81035
Name: salary, Length: 397, dtype: int64

In [ ]:
# indexing using .loc
df.loc[:, ['rank', 'salary']].head()

rank  salary
0      Prof  139750
1      Prof  173200
2  AsstProf   79750
3      Prof  115000
4      Prof  141500

In [ ]:
#indexing using .iloc
df.iloc[:, [5,6]].head()

sex  salary
0  Male  139750
1  Male  173200
2  Male   79750
3  Male  115000
4  Male  141500

### Filtering DataFrame with Boolean

Dapat dikatakan jika filtering dataframe dengan boolean **is more human**. karena kita mengakses suatu data berdasarkan logika dan dapat kita masukan ke dalam suatu statement, sebagai contoh, ‘Ambilkan data yang memiliki nilai luas lebih dari 50’. ketika mengubahnya kedalam suatu kode python cukup dengan menuliskan ```df>50```. maka akan menghasillkan sua tu data Boolean Series berisi Ya (```True```) dan Tidak (```False```).

Filtering data frame dimula dari pertanyaan, pada contoh ini kita akan menjawab pertanyaan :
1. Tunjukan kepada saya semua data orang-orang yang menjadi assisten professor.
2. Tunjukan kepada saya professor dengan jenis kelamin laki-laki
3. Tunjukan kepada saya Tunjukan kepada saya professor dengan jenis kelamin laki-laki dengan gaji diatas 200000


In [ ]:
# 1. Tunjukan kepada saya semua data orang-orang yang menjadi assisten professor.

## Boolean series orang dengan rank Assisten Prof

df['rank'] == "AsstProf"


0      False
1      False
2       True
3      False
4      False
       ...  
392    False
393    False
394    False
395    False
396     True
Name: rank, Length: 397, dtype: bool

In [ ]:
## masukan Booleaan series kedalam data frame

df[df['rank'] == "AsstProf"]

id      rank discipline  yrs.since.phd  yrs.service   sex  salary
2      3  AsstProf          B              4            3  Male   79750
11    12  AsstProf          B              7            2  Male   79800
12    13  AsstProf          B              1            1  Male   77700
13    14  AsstProf          B              2            0  Male   78000
27    28  AsstProf          B              5            3  Male   82379
..   ...       ...        ...            ...          ...   ...     ...
359  360  AsstProf          A             11            4  Male   78785
376  377  AsstProf          A              4            1  Male   74856
377  378  AsstProf          A              6            3  Male   77081
380  381  AsstProf          A              8            3  Male   75996
396  397  AsstProf          A              8            4  Male   81035

[67 rows x 7 columns]

In [ ]:
# 2. Tunjukan kepada saya professor dengan jenis kelamin laki-laki

In [ ]:
## Boolean series orang dengan jenis kelamin laki-laki
df['sex'] == "Male"

0      True
1      True
2      True
3      True
4      True
       ... 
392    True
393    True
394    True
395    True
396    True
Name: sex, Length: 397, dtype: bool

In [ ]:
## Boolean series orang dengan rank Prof
df['rank'] == "Prof"

0       True
1       True
2      False
3       True
4       True
       ...  
392     True
393     True
394     True
395     True
396    False
Name: rank, Length: 397, dtype: bool

In [ ]:
df[(df['rank'] == "Prof") & (df['sex'] == "Male")]

id  rank discipline  yrs.since.phd  yrs.service   sex  salary
0      1  Prof          B             19           18  Male  139750
1      2  Prof          B             20           16  Male  173200
3      4  Prof          B             45           39  Male  115000
4      5  Prof          B             40           41  Male  141500
6      7  Prof          B             30           23  Male  175000
..   ...   ...        ...            ...          ...   ...     ...
391  392  Prof          A             30           19  Male  151292
392  393  Prof          A             33           30  Male  103106
393  394  Prof          A             31           19  Male  150564
394  395  Prof          A             42           25  Male  101738
395  396  Prof          A             25           15  Male   95329

[248 rows x 7 columns]

In [ ]:
# 3. Tunjukan kepada saya professor dengan jenis kelamin laki-laki dengan gaji diatas 200000

In [ ]:
df['salary'] > 200000

0      False
1      False
2      False
3      False
4      False
       ...  
392    False
393    False
394    False
395    False
396    False
Name: salary, Length: 397, dtype: bool

In [ ]:
df[(df['rank'] == "Prof") & (df['sex'] == "Male") &( df['salary'] > 200000) ]

id  rank discipline  yrs.since.phd  yrs.service   sex  salary
43    44  Prof          B             38           38  Male  231545
249  250  Prof          A             29            7  Male  204000
364  365  Prof          A             43           43  Male  205500

In [ ]:
df

id      rank discipline  yrs.since.phd  yrs.service   sex  salary
0      1      Prof          B             19           18  Male  139750
1      2      Prof          B             20           16  Male  173200
2      3  AsstProf          B              4            3  Male   79750
3      4      Prof          B             45           39  Male  115000
4      5      Prof          B             40           41  Male  141500
..   ...       ...        ...            ...          ...   ...     ...
392  393      Prof          A             33           30  Male  103106
393  394      Prof          A             31           19  Male  150564
394  395      Prof          A             42           25  Male  101738
395  396      Prof          A             25           15  Male   95329
396  397  AsstProf          A              8            4  Male   81035

[397 rows x 7 columns]

In [ ]:
df.loc[200, :]

id                    201
rank             AsstProf
discipline              B
yrs.since.phd           4
yrs.service             4
sex                  Male
salary              92700
Name: 200, dtype: object