<a href="https://colab.research.google.com/github/PajrulPalah/data_analysis_bootcamp/blob/main/phyton/Tugas_Homefun_Muhammad_Pajrul_Palah.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://www.nurulfikri.com/wp-content/uploads/2019/11/Python-logo-all.jpg">







# **HOMEFUN PHYTON**
## **Created By : Muhammad Pajrul Palah**
## **Program Muslim Millenials Bootcamp**

> Dalam Tugas kali ini ada 15 Tugas yang akan dikerjaan sebagai lampiran berikut ini:
> 1. Buatkan biodata kamu dengan memasukkan informasi nama, umur, pekerjaan, alamat, asal kampus/sekolah dan motto hidup. Kemudian munculkan biodata tersebut dengan menggunakan perintah print().
2. Hitunglah luas permukaan balok dengan p = 10, l = 5 dan t =7
3. Hitunglah apakah hasil sisa bagi bilangan 10 dan 3 sama dengan 17 dan 8.4. Hitunglah perkalian antara hasil sisa bagi bilangan 10 dan 3 dengan 17 dan 8.
5. Buatkan 2 buah list, yang pertama berisi 10 nama makanan daerah dan yang kedua berisi 10 nama daerahnya
6. Keluarkan nilai ketiga dari list pertama dan nilai ke 9 dari lis kedua
7. Gabungkan kedua list yang sudah dibuat
8. Tambahkan satu makanan baru kedalam list pertama, masukkan makanan tersebut di posisi ke lima dalam list
9. Buat dictionary yang berisi 5 data, key nya adalah daerah dan valuenya adalah kain tradisional daerah tersebut
10. Tambahkan elemen pada dictionary itu dengan 2 daerah dan 2 kain tradisionalnya
11. Buatkan 3 buah set yaitu A, B dan Cyang berisi nama-nama anak indonesia, kemudian lakukan operasi himpunan pada set tersebut (1. A gabung B, 2. A irisan C, 3. A gabung C irisan B)
12. Buatkan fungsi untuk menghitung luas bangun datar layang-layang
13. Buatkan kondisional if else untuk menentukan ranking seseorang, dengan ketentuan (rank A memiliki nilai  < 80, rank B memiliki nilai diantara 70 sampai 79, rank C memiliki nilai diantara 60 sampai 69 dan rank D memiliki nilai < 60)
14. Buatkan numpy array dengan dimensi (3, 5) dan gabungkan dengan numpy array dengan dimensi (5, 1)
15. Bacalah sebuah data apapun itu dengan module pandas, kemudian berikan gambaran datanya dalam bentuk kalimat.

### **1. Biodata Penulis**



Dalam bagian ini penulis akan memberikan informasi berupa :
* Nama Lengkap,
* Umur,
* Pekerjaan,
* Alamat,
* Asal Kampus/Sekolah dan
*  Motto Hidup Jika Hidup :)

In [ ]:
# Biodata Penulis
"""
Nama Saya Adalah Muhammad Pajrul Palah Lahir Di Karawang
Hobi Saya Bermain Bola yang berhubungan dengan bola saya suka
dan ini adalah contoh komentar multi-baris (lines)
"""
# langsung praktik data diri dengan phyton
nama_depan = "Muhammad"
nama_tengah = "pajrul"
nama_belakang = "Palah"
nama_saya = nama_depan +" "+ nama_tengah +" "+ nama_belakang
from datetime import datetime
tahun_lahir = 2001
tahun_sekarang = datetime.now().year
umur = tahun_sekarang - tahun_lahir
pekerjaan = "Pengacara (Pengangguran Banyak Acara)"
alamat = "kota industri terbaik di jawa barat"
asal_kampus = "President University tapi bukan anak Presiden"
motto_hidup = "Berlomba-lomba dalam kebaikan, life is a test and trust, starts small think big and big impact"

# running code
print("Nama Saya :",nama_saya)
print("Umur Saya :", umur)
print("Pekerjaan Saya :", pekerjaan)
print("Alamat Saya", alamat)
print("Asal Kampus :", asal_kampus)
print("Motto Hidup Saya :", motto_hidup)



Nama Saya : Muhammad pajrul Palah
Umur Saya : 22
Pekerjaan Saya : Pengacara (Pengangguran Banyak Acara)
Alamat Saya kota industri terbaik di jawa barat
Asal Kampus : President University tapi bukan anak Presiden
Motto Hidup Saya : Berlomba-lomba dalam kebaikan, life is a test and trust, starts small think big and big impact


In [ ]:
# karena belum rapi kita coba revisi
# Mencari panjang terpanjang dari label
panjang_label_terpanjang = max(len("Nama Saya"), len("Umur Saya"), len("Pekerjaan Saya"), len("Alamat Saya"), len("Asal Kampus"), len("Motto Hidup Saya"))

# Membuat format cetak
format_cetak = "{:<" + str(panjang_label_terpanjang) + "}: {}"

# Menampilkan data
print("Biodata Penulis")
print(format_cetak.format("Nama Saya", nama_saya))
print(format_cetak.format("Umur Saya", umur))
print(format_cetak.format("Pekerjaan Saya", pekerjaan))
print(format_cetak.format("Alamat Saya", alamat))
print(format_cetak.format("Asal Kampus", asal_kampus))
print(format_cetak.format("Motto Hidup Saya", motto_hidup))


Biodata Penulis
Nama Saya       : Muhammad Pajrul Palah
Umur Saya       : 22
Pekerjaan Saya  : Pengacara (Pengangguran Banyak Acara)
Alamat Saya     : kota industri terbaik di jawa barat
Asal Kampus     : President University tapi bukan anak Presiden
Motto Hidup Saya: Berlomba-lomba dalam kebaikan, life is a test and trust, starts small think big and big impact


### **2. Menghitung Luas**
Pada contoh kasus dalam luas permukaan balok dengan p = 10, l = 5 dan t =7

In [ ]:
# kasus luar permukaan balok
# diketahui p = panjang l = lebar dan t = tinggi
# dan nilai p, l dan t sebagai berikut:
p = 10
l = 5
t = 7
# rumus luas permukaan balok adalah : luas_permukaan = 2 * (p * l + p * t + l * t)
# maka:
2 * ((p * l) + (p * t) + (l * t))
#menggunakan variabel
hasil = 2 * ((p * l) + (p * t) + (l * t))
print("Hasil luas permukaan balok adalah =", hasil)
## sekalian volume
volume = p * l * t
print("Hasil volume balok adalah =", volume)

Hasil luas permukaan balok adalah = 310
Hasil volume balok adalah = 350


### **3. Menghitung Hasil Sisa Bagi Bilangan**
Apakah hasil sisa bagi bilangan 10 dan 3 sama dengan 17 dan 8.4. Hitunglah perkalian antara hasil sisa bagi bilangan 10 dan 3 dengan 17 dan 8.4 ?


In [ ]:
# Menghitung hasil sisa bagi bilangan menggunakan operator % pada kasus di atas dapat dikerjakan sebagai berikut:

# Menghitung hasil sisa bagi bilangan 10 dan 3
sisa_10_dan_3 = 10 % 3

# Menghitung hasil sisa bagi bilangan 17 dan 8.4
sisa_17_dan_8_4 = 17 % 8.4

# Apakah hasil sisa bagi kedua itu sama mari kita buktikan
sama = sisa_10_dan_3 == sisa_17_dan_8_4

# Perkalian Antara hasil sisa bagi 10 dan 3 dengan 17 dan 8.4 sebagai berikut :
perkalian = sisa_10_dan_3 * sisa_17_dan_8_4

# Maka Hasilnya adalah
# Menggunakan satu perintah print
print(f"Hasil sisa bagi 10 dibagi (%) 3 = {sisa_10_dan_3}\n"
      f"Hasil sisa bagi 17 dibagi (%) 8.4 = {sisa_17_dan_8_4 }\n"
      f"Apakah hasil sisa bagi sama?= {sama}\n"
      f"Perkalian hasil sisa bagi antara 10 & 3 dengan 17 & 8.4 = {perkalian}")



Hasil sisa bagi 10 dibagi (%) 3 = 1
Hasil sisa bagi 17 dibagi (%) 8.4 = 0.1999999999999993
Apakah hasil sisa bagi sama?= False
Perkalian hasil sisa bagi antara 10 & 3 dengan 17 & 8.4 = 0.1999999999999993


### **4. Membuat List**
No 4 nya tidak ada  
Buatkan 2 buah list, yang pertama berisi 10 nama makanan daerah dan yang kedua berisi 10 nama daerahnya

In [ ]:
# Membuat list makanan dan asal dan asal daerahnya khusus untuk khas Jawa Barat
makanan_khas_jawabarat = [
    "Mie Kocok Bandung",
    "Sate Maranggi Hj Yetti",
    "Lapis Talas Bogor",
    "Dodol Chocodot",
    "Tauco",
    "Citruk",
    "Empal Gentong",
    "Bacetrok",
    "Nasi Tutug Oncom",
    "Nasi Lengko"
]
asal_daerah = [
    "Bandung",
    "Purwakarta",
    "Bogor",
    "Garut",
    "Cianjur",
    "Tasikmalaya",
    "Cirebon",
    "Karawang",
    "Sukabumi",
    "Indramayu"
]

print(makanan_khas_jawabarat)
print(asal_daerah)



['Mie Kocok Bandung', 'Sate Maranggi Hj Yetti', 'Lapis Talas Bogor', 'Dodol Chocodot', 'Tauco', 'Citruk', 'Empal Gentong', 'Bacetrok', 'Nasi Tutug Oncom', 'Nasi Lengko']
['Bandung', 'Purwakarta', 'Bogor', 'Garut', 'Cianjur', 'Tasikmalaya', 'Cirebon', 'Karawang', 'Sukabumi', 'Indramayu']


### **5. Mengeluarkan Nilai Dari List**
Keluarkan nilai ketiga dari list pertama dan nilai ke 9 dari list kedua

In [ ]:
# Mengakses nilai dari list
# Perlu diingat index list dimulai dari angka nol
# Maka angka list nilai ke-3 = [2] dan list nilai ke-9 = [8]

# Mengakses nilai ketiga dari list pertama (indeks 2)
nilai_pertama = makanan_khas_jawabarat[2]

# Mengakses nilai kesembilan dari list kedua (indeks 8)
nilai_kedua = asal_daerah[8]

print("Nilai ketiga dari list pertama =", nilai_pertama)
print("Nilai kesembilan dari list kedua =", nilai_kedua)


Nilai ketiga dari list pertama = Lapis Talas Bogor
Nilai kesembilan dari list kedua = Sukabumi


### **6. Menggabungkan Kedua List**
Gabungkan kedua list yang sudah dibuat

In [ ]:
# List makanan khas Jawa Barat
makanan_khas_jawabarat = [
    "Mie Kocok Bandung",
    "Sate Maranggi Hj Yetti",
    "Lapis Talas Bogor",
    "Dodol Chocodot",
    "Tauco",
    "Citruk",
    "Empal Gentong",
    "Bacetrok",
    "Nasi Tutug Oncom",
    "Nasi Lengko"
]

# List asal daerah
asal_daerah = [
    "Bandung",
    "Purwakarta",
    "Bogor",
    "Garut",
    "Cianjur",
    "Tasikmalaya",
    "Cirebon",
    "Karawang",
    "Sukabumi",
    "Indramayu"
]

# Menggabungkan kedua list
gabungkan_makanan_asal_daerah = makanan_khas_jawabarat + asal_daerah

print(gabungkan_makanan_asal_daerah)


['Mie Kocok Bandung', 'Sate Maranggi Hj Yetti', 'Lapis Talas Bogor', 'Dodol Chocodot', 'Tauco', 'Citruk', 'Empal Gentong', 'Bacetrok', 'Nasi Tutug Oncom', 'Nasi Lengko', 'Bandung', 'Purwakarta', 'Bogor', 'Garut', 'Cianjur', 'Tasikmalaya', 'Cirebon', 'Karawang', 'Sukabumi', 'Indramayu']


In [ ]:
# Menggabungkan menjadi berderet
makanan_dan_daerah = []
for i in range(len(makanan_khas_jawabarat)):
    makanan = makanan_khas_jawabarat[i]
    daerah = asal_daerah[i]
    makanan_dan_daerah.append(f"{makanan} ({daerah})")

# Menampilkan hasil penggabungan
for item in makanan_dan_daerah:
    print(item)

Mie Kocok Bandung (Bandung)
Sate Maranggi Hj Yetti (Purwakarta)
Lapis Talas Bogor (Bogor)
Dodol Chocodot (Garut)
Jambal roti (Pangandaran)
Tauco (Cianjur)
Citruk (Tasikmalaya)
Empal Gentong (Cirebon)
Bacetrok (Karawang)
Nasi Tutug Oncom (Sukabumi)
Nasi Lengko (Indramayu)


### **7. Melakukan Insert Pada List**
## Tambahkan satu makanan baru kedalam list pertama, masukkan makanan tersebut di posisi ke lima dalam list

In [ ]:
# Makanan baru dan asal daerah baru
makanan_baru = "Jambal Roti"
daerah_baru = "Pangandaran"

# Memasukkan makanan baru ke dalam list pertama pada posisi kelima berarti index = [4]
makanan_khas_jawabarat.insert(4, makanan_baru)
asal_daerah.insert(4, daerah_baru)

# Mencetak list yang telah diperbarui
print("List makanan khas Jawa Barat (setelah penambahan):")
print(makanan_khas_jawabarat)

print("List asal daerah (setelah penambahan):")
print(asal_daerah)



List makanan khas Jawa Barat (setelah penambahan):
['Mie Kocok Bandung', 'Sate Maranggi Hj Yetti', 'Lapis Talas Bogor', 'Dodol Chocodot', 'Jambal Roti', 'Jambal roti', 'Tauco', 'Citruk', 'Empal Gentong', 'Bacetrok', 'Nasi Tutug Oncom', 'Nasi Lengko']
List asal daerah (setelah penambahan):
['Bandung', 'Purwakarta', 'Bogor', 'Garut', 'Pangandaran', 'Pangandaran', 'Cianjur', 'Tasikmalaya', 'Cirebon', 'Karawang', 'Sukabumi', 'Indramayu']


### **8. Membuat Dictionary**
Buat dictionary yang berisi 5 data, key nya adalah daerah dan valuenya adalah kain tradisional daerah tersebut

In [ ]:
kain_tradisional = {
    "Jawa Barat": "Batik Mega Mendung Cirebon",
    "Riau": "Tenun Siak",
    "Aceh": "Kerawang Gayo",
    "Kalimantan Barat": "Kain Sintang / Ikat Dayak",
    "Nusa Tenggara Timur": "Kain Tenun Ikat"
}
print(kain_tradisional)


{'Jawa Barat': 'Batik Mega Mendung Cirebon', 'Riau': 'Tenun Siak', 'Aceh': 'Kerawang Gayo', 'Kalimantan Barat': 'Kain Sintang / Ikat Dayak', 'Nusa Tenggara Timur': 'Kain Tenun Ikat'}


### **9. Menambahkan Elemen Pada Dictionary**
Tambahkan elemen pada dictionary itu dengan 2 daerah dan 2 kain tradisionalnya


In [ ]:
# Menambahkan dua elemen ke dalam dictionary
kain_tradisional["Bali"] = "Kain Poleng"
kain_tradisional["Sulawesi Selatan"] = "Lipa Sabbe"

# Mencetak dictionary yang telah diperbarui setelah penambahan
print(kain_tradisional)

{'Jawa Barat': 'Batik Mega Mendung Cirebon', 'Riau': 'Tenun Siak', 'Aceh': 'Kerawang Gayo', 'Kalimantan Barat': 'Kain Sintang / Ikat Dayak', 'Nusa Tenggara Timur': 'Kain Tenun Ikat', 'Bali': 'Kain Poleng', 'Sulawesi Selatan': 'Lipa Sabbe'}


### **10. Melakukan Operasi Himpunan Pada 3 Buah Data Set**

Buatkan 3 buah set yaitu A, B dan Cyang berisi nama-nama anak indonesia, kemudian lakukan operasi himpunan pada set tersebut (1. A gabung B, 2. A irisan C, 3. A gabung C irisan B)

In [ ]:
# Set A berisi nama-nama anak Sunda Pride
A = {"Encep", "Udin", "Asep", "Esih", "Pajrul"}

# Set B berisi nama-nama anak Sunda Pride
B = {"Nopi", "Asep", "Tatang", "Aceng", "Eis"}

# Set C berisi nama-nama anak Sunda Pride
C = {"Esih", "Titi", "Tatang", "Pajrul", "Encep"}



# Operasi himpunan:
# 1. A gabung B
gabung_AB = A.union(B)

# 2. A irisan C
irisan_AC = A.intersection(C)

# 3. A gabung (C irisan B)
gabung_AC_irisan_B = A.union(C.intersection(B))

# Mencetak hasil operasi himpunan
print("1. A gabung B:", gabung_AB)
print("2. A irisan C:", irisan_AC)
print("3. A gabung (C irisan B):", gabung_AC_irisan_B)


1. A gabung B: {'Udin', 'Pajrul', 'Tatang', 'Eis', 'Asep', 'Nopi', 'Esih', 'Aceng', 'Encep'}
2. A irisan C: {'Encep', 'Pajrul', 'Esih'}
3. A gabung (C irisan B): {'Tatang', 'Asep', 'Esih', 'Encep', 'Udin', 'Pajrul'}


### **11. Menghitung Luas Bangun Layang-Layang**
Buatkan fungsi untuk menghitung luas bangun datar layang-layang.



In [ ]:
"""
Untuk menghitung luas bangun datar layang-layang, Anda dapat menggunakan rumus:

Luas = 1/2 * (d1 * d2)

di mana:
d1 adalah panjang diagonal pertama.
d2 adalah panjang diagonal kedua.
Jika diketahui bahwa panjangan diagonal pertama [d1] adalah 65 cm
dan panjang diagonal kedua [d2] adalah 42 cm
"""
# Mulai Menhitung
d1 = 65
d2 = 42
luas_layang_layang = (d1 * d2)/2
print(luas_layang_layang)

# atau dengan cara lainnya dan nilai float
def luas_layang_layang(d1, d2):
    luas = (d1 * d2) / 2
    return luas
panjang_diagonal1 = 65.68
panjang_diagonal2 = 42.91
hasil_luas = luas_layang_layang(panjang_diagonal1, panjang_diagonal2)

# Menggunakan fungsi round 4 angka di belakang koma
hasil_luas_round = round(hasil_luas,4)
print("Luas layang-layang adalah:", hasil_luas_round)


1365.0
Luas layang-layang adalah: 1409.1644


### **12. Membuat Kondisi IF Else**
Buatkan kondisional if else untuk menentukan ranking seseorang, dengan ketentuan (rank A memiliki nilai  < 80, rank B memiliki nilai diantara 70 sampai 79, rank C memiliki nilai diantara 60 sampai 69 dan rank D memiliki nilai < 60)

In [ ]:
# Mendefinisikan nilai
nilai = 91

# Menentukan ranking
if nilai < 60:
    ranking = "Rank D"
    pesan = "Tidak Lulus Wajib Remed"
    pesan_1 = "Ada yang salah dengan anda!"
elif 60 <= nilai < 70:
    ranking = "Rank C"
    pesan = "Tidak Lulus Wajib Remed"
    pesan_1 = "Kurang Semangat"
elif 70 <= nilai < 80:
    ranking = "Rank B"
    pesan = "Lulus"
    pesan_1 = "Cukup Bangga Orangtua Mu Nak!"
elif 80 <= nilai <= 90:
    ranking = "Rank A"
    pesan = "Lulus"
    pesan_1 = "Anak Rajin Kebanggaan Sekolah Nih"
else:
    ranking = "Rank A"
    pesan = "Lulus"
    pesan_1 = "Cerdas Paten Kali Lah"

# Menampilkan ranking dan pesan
print("Nilai Anda:", nilai)
print("Ranking Anda:", ranking)
print("Pesan:", pesan)
print("Wejangan:", pesan_1)

Nilai Anda: 91
Ranking Anda: Rank A
Pesan: Lulus
Wejangan: Cerdas Paten Kali Lah


### **13. Membuat Numpy Array**
Buatkan numpy array dengan dimensi (3, 5) dan gabungkan dengan numpy array dengan dimensi (5, 1)

In [ ]:
import numpy as np

# Membuat numpy array dengan dimensi (3, 5)
array_1 = np.array([
                    [1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10],
                    [11, 12, 13, 14, 15]
                    ])

# Membuat numpy array dengan dimensi (5, 1) kayanya dimensi [1,5] yang bener

array_2 = np.array([
                    #
                    [16,17,18,19,20]
                    ])

np.concatenate([array_1, array_2])


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
# sekarang kita samakan dimensi row nya pada contoh berikut

# Mengganti numpy array dengan dimensi (5, 3)
array_1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10,11,12],
                    [13,14,15]])

# Membuat numpy array dengan dimensi (5, 1)
array_2 = np.array([[16],
                    [17],
                    [18],
                    [19],
                    [20]
                    ])

# Menggabungkan kedua array tapi secara horizontal
gabung_array = np.hstack((array_1, array_2))


# Mencetak hasil gabungan
print("Array hasil gabungan:")
print(gabung_array)


Array hasil gabungan:
[[ 1  2  3 16]
 [ 4  5  6 17]
 [ 7  8  9 18]
 [10 11 12 19]
 [13 14 15 20]]


**Jadi Pada Intinya rownya harus sama agar bisa digabungkan (joining). kayanya sih gitu saya juga puyeung udah coba berapa kali belum menemukan pencerahan**

### **14. Membaca Data Dengan Module Pandas AS pd**
Bacalah sebuah data apapun itu dengan module pandas, kemudian berikan gambaran datanya dalam bentuk kalimat.

In [ ]:
# Menggunakan Module Pandas
import pandas as pd

# Membaca file CSV
data = pd.read_csv("movies-db.csv")

# Menampilkan informasi umum tentang data
print("Informasi Umum:")
data.info()

# Menampilkan beberapa baris pertama data
print("\nBeberapa Baris Pertama Data:")
print(data.head())

# Menampilkan ringkasan statistik data
print("\nRingkasan Statistik Data:")
print(data.describe())


Informasi Umum:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   name             30 non-null     object 
 1   year             30 non-null     int64  
 2   length_min       30 non-null     int64  
 3   genre            30 non-null     object 
 4   average_rating   30 non-null     float64
 5   cost_millions    30 non-null     float64
 6   foreign          30 non-null     int64  
 7   age_restriction  30 non-null     int64  
dtypes: float64(2), int64(4), object(2)
memory usage: 2.0+ KB

Beberapa Baris Pertama Data:
                 name  year  length_min      genre  average_rating  \
0           Toy Story  1995          81  Animation             8.3   
1               Akira  1998         125  Animation             8.1   
2  The Breakfast Club  1985          97      Drama             7.9   
3          The Artist  2011         100    Romance

In [ ]:
data.head()

name  year  length_min      genre  average_rating  \
0           Toy Story  1995          81  Animation             8.3   
1               Akira  1998         125  Animation             8.1   
2  The Breakfast Club  1985          97      Drama             7.9   
3          The Artist  2011         100    Romance             8.0   
4        Modern Times  1936          87     Comedy             8.6   

   cost_millions  foreign  age_restriction  
0           30.0        0                0  
1           10.4        1               14  
2            1.0        0               14  
3           15.0        1               12  
4            1.5        0               10

In [ ]:
# Filter data untuk hanya menyertakan film dengan genre "Animation"
animation_movies = data[data['genre'] == 'Animation']

# Menghitung jumlah film yang memiliki genre "Animation"
jumlah_film_animation = len(animation_movies)

print("Jumlah film dengan genre 'Animation':", jumlah_film_animation)


Jumlah film dengan genre 'Animation': 2


In [ ]:
# Temukan film dengan durasi terpanjang
film_terpanjang = data[data['length_min'] == data['length_min'].max()]

# Ambil nama file dan durasinya
nama_filem = film_terpanjang['name'].values[0]
panjang_durasi = film_terpanjang['length_min'].values[0]

print("Film dengan durasi terpanjang:")
print("Nama Film:", nama_filem)
print("Panjang Durasi (menit):", panjang_durasi)


Film dengan durasi terpanjang:
Nama Film: Blue is the Warmest Colour
Panjang Durasi (menit): 179


In [ ]:
# Temukan film dengan rating tertinggi
film_tertinggi = data[data['average_rating'] == data['average_rating'].max()]

# Ambil nama film, genre, dan tahun rilis
nama_film = film_tertinggi['name'].values[0]
genre = film_tertinggi['genre'].values[0]
tahun_rilis = film_tertinggi['year'].values[0]

print("Film dengan Rating Tertinggi:")
print("Nama Film:", nama_film)
print("Genre:", genre)
print("Tahun Rilis:", tahun_rilis)


Film dengan Rating Tertinggi:
Nama Film: The Shawshank Redemption
Genre: Crime
Tahun Rilis: 1994


## **Burung Kipasan Burung Cendrawasih**
## **Cukup Sekian Dan Terima Kasih**